### ISSUE TITLE
Setup Github organization and repository

### ISSUE THREAD

**Issue by computate** [opendatapolicing/opendatapolicing#1]
### Create a Github organization

As the instructor of the course, setup a new Github organization with a unique name. You will need to sign into github and share the organization with all the instructors involved. 

https://github.com/

Click the [ + ] button in the top right corner, then "New Organization". Click [ Join for free ]. 

* Give the Organization account name a unique name with dashes, not spaces. 
* Provide a contact email of one of the instructors. 
* This organization belongs to: My personal account

Click [ Next ]. 

Search for usernames to add to the organization here, then click [ Complete Setup ]. 

Fill in the survey questions, then click [ Submit ]. 

### Fork the computate-org repository into the Github organization

Visit: https://github.com/computate-org/computate-org

Click the [ Fork ] button in the top right. 

Select the Github organization you created earlier. 

### Rename the computate-org repository to a unique name for the organization

To manage many courses over time, it will help to rename the repository for each organization to keep track of them over time. 

Click the "Settings" tab on the forked repository and change the repository name to a unique name, then click [ Rename ]. 

# Add admin users to the repository

Click the "Settings" tab on the forked repository, select "Manage access", then click [ Invite teams or people ] and add the instructors as admins on the repository. 

# Enable issues in the repository

Click the "Settings" tab on the forked repository and check "Issues" so issues can be added to the repository. 

### Clone the computate-org repository

On the "Code" tab of the forked repository, click the [ Code ] button, select the SSH URL and copy it to the clipboard. Then clone the repository to your computer in a new directory, where "???" is the unique organization or unique repository name. 

```bash
sudo install -d -o $USER -g $USER /usr/local/src/???
git clone git@github.com:???/???.git /usr/local/src/???
cd /usr/local/src/???
```

Setup the upstream repository to pull updates from the upstream repository. 

```bash
git remote add upstream git@github.com:computate-org/computate-org.git

git fetch upstream
git merge upstream/master

# or

git pull upstream master
```

### Create an Ansible hosts file for the instructor

First create the directory for the instructor inventory. 

```bash
install -d /usr/local/src/opendatapolicing/inventories/instructor
```

Create a hosts file for your development inventory. Add your hostname to each of the following host groups so that ansible can run each of these playbooks on your host. 

```bash
echo "
[computate_org]
localhost
" > /usr/local/src/opendatapolicing/inventories/instructor/hosts
```

### Create an Ansible vault for the instructor secrets

As an instructor, create and edit an encrypted ansible vault with the information about the team taking the course, organization, and repositories.

```bash
install -d /usr/local/src/opendatapolicing/inventories/instructor/host_vars/localhost/
ansible-vault create /usr/local/src/opendatapolicing/inventories/instructor/host_vars/localhost/vault
ansible-vault edit /usr/local/src/opendatapolicing/inventories/instructor/host_vars/localhost/vault
```

The contents of the vault will contain the secrets needed to override any default values you want to change in defining the course.

https://github.com/computate-org/computate-org/blob/master/roles/computate_org_github/defaults/main.yml

Here is an example of the contents of the ansible vault for the course: 

```yaml

# The unique team id without spaces. 
TEAM_ID: "mce1"
# The name of the Github organization for the course. 
GITHUB_ORG: "computate-org-{{ TEAM_ID }}"
# The github token of the instructor's Github account. See Github Settings, Developer Settings, Personal access tokens. 
# Make sure the token has the following roles (admin:org, repo): https://github.com/settings/tokens
GITHUB_TOKEN: "..."
# The name of the forked Github repository for the course containing the ansible scripts and ansible vaults for the project. 
GITHUB_REPO_NAME: "computate-org-{{ TEAM_ID }}"
# The path to the cloned repository. 
GITHUB_REPO_PATH: "/usr/local/src/{{ GITHUB_REPO_NAME }}"
# The SSH URL to the git repository. 
GITHUB_REPO: "git@github.com:{{ GITHUB_ORG }}/{{ GITHUB_REPO_NAME }}.git"
# The same repository name or a different one if the Ansible vaults are kept in a private repository. 
ANSIBLE_REPO_NAME: "{{ GITHUB_REPO_NAME }}"
# The same repository path or a different one if the Ansible vaults are kept in a private repository. 
ANSIBLE_REPO_PATH: "/usr/local/src/{{ ANSIBLE_REPO_NAME }}"
# The same repository SSH URL or a different one if the Ansible vaults are kept in a private repository. 
ANSIBLE_REPO: "git@github.com:{{ GITHUB_ORG }}/{{ ANSIBLE_REPO_NAME }}.git"
# The display name of the Github project. 
PROJECT_NAME: "School Mock Client Engagement"
# The description of the Github project. 
PROJECT_DESCRIPTION: "A mock client engagement project to setup the app. "
# The name of the application to deploy. 
APP_NAME: computate-scolaire
# The git repository name of the application to deploy. 
APP_REPO_NAME: "{{ APP_NAME }}"
# The path to the cloned repository of the application to deploy. 
APP_REPO_PATH: "/usr/local/src/{{ APP_REPO_NAME }}"
# The SSH URL to the repository of the application to deploy. 
APP_REPO: "git@github.com:{{ GITHUB_ORG }}/{{ APP_REPO_NAME }}.git"
# The Ansible friendly name of the the repository of the application to deploy. 
APP_NAME_ANSIBLE: "{{ APP_NAME | regex_replace('-', '_') }}"

# The URL to the OpenShift cluster to deploy. 
REDHAT_OPENSHIFT_HOST: https://console.rh-us-east-1.openshift.com
# The URL to manage the OpenShift cluster to deploy. 
REDHAT_OPENSHIFT_MANAGE_HOST: https://employee.openshift.com
# The OpenShift project name that will be used. 
REDHAT_OPENSHIFT_NAMESPACE: school
# The OpenShift login IDs that will be managing the OpenShift cluster. 
REDHAT_OPENSHIFT_LOGIN_IDS: 
  - christophertate

```

Once your Ansible hosts and vault are configured, you can run the ansible-playbook to generate the Github project board, columns, milestones, issues and cards. 

```bash
(cd /usr/local/src/??? && ansible-playbook instructor.yml -i inventories/instructor/hosts --vault-id @prompt)
```

Now view the results in github in your organization!
